export const ALL_SALES_REQUEST = "ALL_SALES_REQUEST";
export const ALL_SALES_SUCCESS = "ALL_SALES_SUCCESS";
export const ALL_SALES_FAILURE = "ALL_SALES_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";